# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_version = "3.2.16"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
  # Configure hostmanager and vbguest plugins
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.vbguest.auto_update = false

  # Ansible controller
  config.vm.define "ansible", primary: true do |ansible|
    ansible.vm.hostname = "xxx-aisi2021-ansible"
    ansible.vm.network :private_network, ip: "192.168.100.10"
    ansible.vm.provision "shell", path: "provisioning/ansible-controller.sh"
  end

  # Application server
  config.vm.define "nodeapp" do |app|
    app.vm.hostname = "xxx-aisi2021-nodeapp"
    app.vm.network :private_network, ip: "192.168.100.11"
    app.vm.provision "shell", path: "provisioning/servers.sh"
  end

  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = "xxx-aisi2021-db"
    db.vm.network :private_network, ip: "192.168.100.12"
    db.vm.provision "shell", path: "provisioning/servers.sh"
  end
end
